"""added new status field to user_data model

Revision ID: 4beaf4d2123b
Revises: efca5a609c91
Create Date: 2023-10-10 22:49:27.154101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4beaf4d2123b'
down_revision = 'efca5a609c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('pending', 'accepted', 'rejected', name='status_enum').create(op.get_bind())
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('pending', 'accepted', 'rejected', name='status_enum', create_type=False), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_column('status')

    sa.Enum('pending', 'accepted', 'rejected', name='status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
