"""added models

Revision ID: d819db9415d1
Revises: 
Create Date: 2023-10-09 22:38:10.261592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd819db9415d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('national_id', sa.String(length=10), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('photo1_s3_url', sa.String(length=255), nullable=False),
    sa.Column('photo2_s3_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('photo1_s3_url'),
    sa.UniqueConstraint('photo2_s3_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_data')
    # ### end Alembic commands ###
